### PR TITLE
Add per material settings: shade color and shade softness

### LINKED ISSUE #7: BUG: Implemented receive shadow prop
The receive shadow parameter is not working properly.
The shadows casted in the scene are not respecting the "Receive Shadow" from a material parameter.

A 3Dmodel with "Receive Shadow" disable will receive the shadows.
Shadows should be bypassed if the parameter "Receive Shadow" is disable for a material.

_This is related to this closed issue : [celshader and shadows #1](https://github.com/armory3d/driver_celshade/issues/1)
shadows fixed at [d017d9a ](https://github.com/armory3d/driver_celshade/commit/d017d9add3fb5eac6ed999845ca0b15871166f9f) (although only sun light is implemented)_

unfortunately emission and receive shadows are still not working properly.

### PR DESCRIPTION
**Pull request by MoritzBrueckner**
Requires https://github.com/armory3d/armory/pull/2018, also the submodule in https://github.com/armory3d/driver_celshade_example needs to be updated in case this PR is merged.

UI screenshot

- `Shade Color (Multiply)` defines a color that is multiplied with the base color in the direct color shaded part of the mesh. This implements/fixes https://github.com/armory3d/driver_celshade/issues/7, if you want a flat mesh you can now choose white as the shade color.
- `Shade Softness` is the amount of the soft gradient between lit and shaded parts. A value of 0.0 (min) means a sharp edge, 0.5 (max) means a full gradient over the entire mesh (because the edge is smoothed over the interval [0.5 - softness, 0.5 + softness]).

The default values are chosen to not change anything visually compared to older files like the celshade forest example.

Example screenshot

Should there also be global properties for this that can be overriden by the material (with a checkbox)?

### CODE REVIEW

**Comment by onelsonic** [comment]
this is a toon shader awesomeness! :tada:
as per, _should there also be global properties for this that can be overriden by the material (with a checkbox)?_

I will say, in a perfect world we should be able to control at least the shading multiply color per material as well.

Edit: but is some case, the color shading can be better looking and simpler to implement from a texture and not a solid color.

**Comment by MoritzBrueckner** [comment]
Thanks :) Sorry I think a was a bit unclear: this is already a per-material property. The question was if there should be a global property as well because currently you would have to change every material if you want a unique shading color for example.

In the future we could add rim and specular lighting although I don't know what exactly the scope of this driver is.

**Comment by onelsonic** [comment]
👍 yes having a global setting can be useful.
all about activating the shading is great.

How to to specify 
The part about the color shading (multiply), I've checked some implementation of the toon shader from an artistic perspective and when it comes to colors they use:

- a base color or base texture
- a sss color (which is multiplied) or sss texture
and then
- a specular color  or specular texture

in the Principled BSDF we can use:
Base Color
Subsurface Color

https://forum.unity.com/threads/guilty-gear-xrd-shader-test.448557/

**Comment by onelsonic** [comment]
👍 yes having a global setting can be useful.
all about activating the shading is great and we should keep to possibility to control each material individually.

Then how do you specify a "Shade Color (Multiply)" for a particular 3d object?
I've checked some toon shader implementation and when it comes to colors they use the following :

- a solid base color or base texture or a colorRamp (color info)
- a sss color (that is multiplied) or sss texture (color info)
and then optionally
- a specular color or specular texture (grayscale)

we should be able to plug all of this in the Principled BSDF :
Base Color
Subsurface Color
specular

Guilty gear Xrd (then FighterZ, from the same studio) has one of the best realtime toon shader implementation:
GDC presentation : https://www.youtube.com/watch?v=yhGjCzxJV3E&list=PLCNWLAmyc3lPLYweavTcTnPL-abka1pHP
the unity version made by others : https://forum.unity.com/threads/guilty-gear-xrd-shader-test.448557/

**Comment by onelsonic** [comment]
I just applied all the changes to my local repo and it works perfectly using the celshade driver 👍 
and does not affect when I switch back to mobile or Desktop drivers, all good.

I get now how the color is specified for a material.
Rooting the color or texture to an existing graphical process like the Principled BSDF opens more possibility going forward.
If a model has let's say 25 colors for example, the current process is to have one material per colors,
while using textures will be much more flexible, the base color is already processed this way so we just need to check the color of the SSS texture that we can plug in the Subsurface Color for this material and multiply it to get our correct shading toon color.
We just have to define 2 color palettes for a model.

Something like this, where the middle texture is the SSS texture.
TracerTest

**Comment by MoritzBrueckner** [comment]
> Then how do you specify a "Shade Color (Multiply)" for a particular 3d object?

You need to set it in the material. If multiple objects share the same material they also share the shadow color. In theory it would be possible to make this a per-object setting but that would make the UI more complicated again and the shaders as well.

The shader implementation you've linked looks really interesting, but such a thing will probably be difficult to implement (the implementation shown is made with the game in mind, a general solution would probably look a bit different). If we were using the Principled BSDF node for toon shading, there would be a not so small rewrite required for the celshade driver or cycles exporter because the driver currently just uses the default shader generation modules from Armory (with PBR in mind). I think it's common that developers create their own shaders if they need a very distinctive style.

My time is very limited right now but I might implement some rim and specular lighting in the future, add global parameters and make it adjustable whether to multiply or to add colors. That will bring more artistic freedom but of course it will still be far away from the implementation you've mentioned. You are also welcome to open pull requests if you want :)

Also, if you need a very special shader you could try to work with color ramps and create your own shader in the shader editor.

**Comment by onelsonic** [comment]
thanks @MoritzBrueckner 👍 
I was not expecting the possibility to add colors so I checked how other games toon shader proceed with shadow colors and exactly it all depended on the style of the game.
Thanks for your time you already did a lot. Looking at the changes I learn bit by bit how shaders are working internally.
GLSL is new to me.
I will play around with the celshader driver and share if I found anything, so using the Principled BSDF can be done good, that's a good start.
Many Thanks

**Pull request merged**
