### PR TITLE
correcting instancing for Celshade Renderer

### PR DESCRIPTION
**Pull request by onelsonic**
more info on the problem can be found here : https://github.com/armory3d/armory/issues/2212

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
Hi, did you test this with a displacement material? Looks like the entire if/else block (from where you moved only the else part down) should be moved. I hadn't yet time to test this myself as the forest.blend celshading example stopped working for me (for some other reasons I don't know yet) and I first wanted to fix this to be sure everything is working correctly.

**Comment by onelsonic** [comment]
Hi Moritz you're totally right. 👍 I made the displacement disabled with my change.
Moving the all "if" block down made the displacement same as it was before.
I have updated my pull request above.

Also prior to this, "displacement" in the celshade render was not really effective since I think this Celshade render flattens all materials out.

Celshade :
2021-05-29 17_46_04-test
Desktop:
2021-05-29 17_53_17-displacement

I think this should be corrected normal map / displacement never really worked with the Celshade render and this is another issue.
I will create an issue for this, as normally maps/displacement should work in the celshade/Toon renderer.

**Comment by onelsonic** [comment]
I have created another issue about the normally maps/displacement with my example file here : #12

**Comment by onelsonic** [comment]
> 
> 
> Hi, did you test this with a displacement material? Looks like the entire if/else block (from where you moved only the else part down) should be moved. I hadn't yet time to test this myself as the forest.blend celshading example stopped working for me (for some other reasons I don't know yet) and I first wanted to fix this to be sure everything is working correctly.

@MoritzBrueckner : the celshading example stopped working a while ago.
I did some tests with previous version of Armory and the error is now with the Volumetric Light.
I guess some changes were made to the Desktop/Mobile renderers that need to be replicated into the Celshade renderer.
I created an issue for this here : #14

**Pull request merged**
